# python
from typing import Optional, List, Dict, Any
from datetime import datetime

# 3rd party
from pydantic import BaseModel, Field


class BookMetadata(BaseModel):
    """Book metadata for profile creation."""
    
    book_id: str = Field(..., description="Unique book identifier")
    title: str = Field(..., description="Book title")
    author: Optional[str] = Field(None, description="Book author")
    description: Optional[str] = Field(None, description="Book description from Google Books")
    user_notes: Optional[str] = Field(None, description="User's personal notes about the book")
    rating: Optional[float] = Field(None, ge=0.0, le=5.0, description="User rating (0-5)")
    genres: Optional[List[str]] = Field(default_factory=list, description="Book genres")


class BookProfile(BaseModel):
    """Semantic profile of a book generated by Profile Agent."""
    
    book_id: str = Field(..., description="Book identifier")
    themes: List[str] = Field(..., description="Extracted themes from the book")
    genres: List[str] = Field(..., description="Identified genres")
    mood: Optional[str] = Field(None, description="Overall mood/tone of the book")
    complexity: Optional[str] = Field(
        None, 
        description="Reading complexity level (easy/medium/hard)"
    )
    key_concepts: List[str] = Field(
        default_factory=list,
        description="Key concepts or topics discussed"
    )
    similar_to: List[str] = Field(
        default_factory=list,
        description="Names of similar well-known books"
    )
    embedding_id: Optional[str] = Field(
        None,
        description="Reference to embedding in vector DB"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ProfileRequest(BaseModel):
    """Request to create a book profile."""
    
    book_metadata: BookMetadata = Field(..., description="Book metadata")
    user_id: Optional[str] = Field(None, description="User ID for multi-user isolation")


class ProfileResponse(BaseModel):
    """Response with created book profile."""
    
    profile: BookProfile = Field(..., description="Generated book profile")
    embedding_stored: bool = Field(..., description="Whether embedding was stored in vector DB")
    cached: bool = Field(default=False, description="Whether result was served from cache")
    processing_time_ms: Optional[float] = Field(None, description="Processing time in milliseconds")


class HealthCheckResponse(BaseModel):
    """Health check response."""
    
    status: str = Field(..., description="Service status")
    service: str = Field(..., description="Service name")
    version: str = Field(..., description="Service version")
    components: Dict[str, str] = Field(
        default_factory=dict,
        description="Status of service components"
    )
