[project]
name = "profile-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.5",
    "fastapi[standard]>=0.129.0",
    "langgraph>=1.1.2",
    "pydantic-settings>=2.13.0",
    "sentence-transformers>=5.3.0",
]
